<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ureport [
        <!ELEMENT ureport (cell|row|column|datasource|paper)*>
        <!ELEMENT cell (cell-style|simple-value|dataset-value|condition-property-item)*>
        <!ATTLIST cell
                col CDATA #REQUIRED
                expand CDATA #REQUIRED
                name CDATA #REQUIRED
                row CDATA #REQUIRED>
        <!ELEMENT cell-style (left-border|right-border|top-border|bottom-border)*>
        <!ATTLIST cell-style
                align CDATA #IMPLIED
                bgcolor CDATA #IMPLIED
                bold CDATA #IMPLIED
                font-family CDATA #REQUIRED
                font-size CDATA #REQUIRED
                for-condition CDATA #IMPLIED
                forecolor CDATA #IMPLIED
                valign CDATA #IMPLIED>
        <!ELEMENT left-border (#PCDATA)>
        <!ATTLIST left-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT right-border (#PCDATA)>
        <!ATTLIST right-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT top-border (#PCDATA)>
        <!ATTLIST top-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT bottom-border (#PCDATA)>
        <!ATTLIST bottom-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT simple-value (#PCDATA)>
        <!ELEMENT dataset-value (#PCDATA)>
        <!ATTLIST dataset-value
                aggregate CDATA #REQUIRED
                dataset-name CDATA #REQUIRED
                mapping-type CDATA #REQUIRED
                order CDATA #REQUIRED
                property CDATA #REQUIRED>
        <!ELEMENT condition-property-item (cell-style|condition)*>
        <!ATTLIST condition-property-item
                name CDATA #REQUIRED>
        <!ELEMENT condition (value)*>
        <!ATTLIST condition
                op CDATA #REQUIRED
                id CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT value (#PCDATA)>
        <!ELEMENT row (#PCDATA)>
        <!ATTLIST row
                height CDATA #REQUIRED
                row-number CDATA #REQUIRED>
        <!ELEMENT column (#PCDATA)>
        <!ATTLIST column
                col-number CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT datasource (dataset)*>
        <!ATTLIST datasource
                name CDATA #REQUIRED
                type CDATA #REQUIRED
                username CDATA #REQUIRED
                password CDATA #REQUIRED
                url CDATA #REQUIRED
                driver CDATA #REQUIRED>
        <!ELEMENT dataset (sql|field)*>
        <!ATTLIST dataset
                name CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT sql (#PCDATA)>
        <!ELEMENT field (#PCDATA)>
        <!ATTLIST field
                name CDATA #REQUIRED>
        <!ELEMENT paper (#PCDATA)>
        <!ATTLIST paper
                type CDATA #REQUIRED
                left-margin CDATA #REQUIRED
                right-margin CDATA #REQUIRED
                top-margin CDATA #REQUIRED
                bottom-margin CDATA #REQUIRED
                paging-mode CDATA #REQUIRED
                fixrows CDATA #REQUIRED
                width CDATA #REQUIRED
                height CDATA #REQUIRED
                orientation CDATA #REQUIRED
                html-report-align CDATA #REQUIRED
                bg-image CDATA #REQUIRED
                html-interval-refresh-value CDATA #REQUIRED
                column-enabled CDATA #REQUIRED>
        ]>
<ureport><cell expand="None" name="A1" row="1" col="1"><cell-style font-size="9" forecolor="239,239,239" font-family="宋体" bgcolor="33,29,227" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[需求主体]]></simple-value></cell><cell expand="None" name="B1" row="1" col="2"><cell-style font-size="9" forecolor="239,239,239" font-family="宋体" bgcolor="33,29,227" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[需求处理时间（天）]]></simple-value></cell><cell expand="None" name="C1" row="1" col="3"><cell-style font-size="9" forecolor="239,239,239" font-family="宋体" bgcolor="33,29,227" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[上线时间]]></simple-value></cell><cell expand="Down" name="A2" row="2" col="1"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="left" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="time-required" aggregate="group" property="需求主题" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="B2" row="2" col="2"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="left" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="time-required" aggregate="group" property="需求处理时间（天）" order="none" mapping-type="simple"></dataset-value><condition-property-item name="time-required.group(需求处理时间（天）)"><cell-style for-condition="true" font-size="0" font-family="" bgcolor="233,65,65"></cell-style><condition op="&gt;" id="55772360-78f3-11ec-a6b6-1d0f54190fec" type="property"><value><![CDATA[10]]></value></condition></condition-property-item></cell><cell expand="Down" name="C2" row="2" col="3"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="time-required" aggregate="group" property="上线时间" order="none" mapping-type="simple"></dataset-value></cell><row row-number="1" height="19"/><row row-number="2" height="19"/><column col-number="1" width="498"/><column col-number="2" width="303"/><column col-number="3" width="298"/><datasource name="grafana" type="jdbc" username="root" password="password" url="jdbc:mysql://mysql.eazybuilder-devops.cn:3306/grafana?useUnicode=true&amp;useSSL=false&amp;characterEncoding=utf-8" driver="com.mysql.cj.jdbc.Driver"><dataset name="test" type="sql"><sql><![CDATA[SELECT id, name, description, is_in_chlog, `position`, is_in_roadmap, fields_bits, default_status_id
FROM grafana.redmine_trackers]]></sql><field name="id"/><field name="name"/><field name="description"/><field name="is_in_chlog"/><field name="position"/><field name="is_in_roadmap"/><field name="fields_bits"/><field name="default_status_id"/></dataset><dataset name="grafana-index_business.ureport" type="sql"><sql><![CDATA[SELECT
        UNIX_TIMESTAMP(iv.`date`) as 'time',
        iv.value/60 as '分析平均时间(分钟)'
FROM
        index_value iv
left join index_business ib on
        iv.id = ib.index_value_id
WHERE
        index_id = 20
        and ib.index_lever_name = "devops"
order by
        iv.`date` desc
]]></sql><field name="time"/><field name="分析平均时间(分钟)"/></dataset><dataset name="grafana-data-outside-time-range" type="sql"><sql><![CDATA[SELECT
        iv.`date` as 'time',
        iv.value / 86400 as '需求处理效率'
FROM
        index_value iv
left join index_business ib on
        iv.id = ib.index_value_id
WHERE
        index_id = (SELECT id from index_grafana ig  WHERE ig.name='需求处理效率')
        and ib.index_lever_name = "devops"
order by
        iv.`date` desc]]></sql><field name="time"/><field name="需求处理效率"/></dataset><dataset name="time-required" type="sql"><sql><![CDATA[        SELECT
                (SELECT subject from redmine_issues WHERE  id=ist.issues_id) as "需求主题",
                ABS(TIMESTAMPDIFF(DAY ,ist.yi_shang_xian ,ist.dai_ren_ling) ) as '需求处理时间（天）',
                ist.yi_shang_xian as '上线时间'

        FROM
                issues_status_trigger ist
        WHERE
                ist.issues_id in
                (
                        SELECT
                                id
                        FROM
                                redmine_issues ri
                        WHERE
                                ri.project_id =1
                        AND
                    ist.yi_shang_xian is not null
                )
        order by
        ist.yi_shang_xian desc]]></sql><field name="需求主题"/><field name="需求处理时间（天）"/><field name="上线时间"/></dataset></datasource><paper type="A4" left-margin="90" right-margin="90"
                                                                                                                                      top-margin="72" bottom-margin="72" paging-mode="fitpage" fixrows="0"
                                                                                                                                      width="595" height="842" orientation="portrait" html-report-align="left" bg-image="" html-interval-refresh-value="0" column-enabled="false"></paper></ureport>