<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ureport [
        <!ELEMENT ureport (cell|row|column|datasource|paper)*>
        <!ELEMENT cell (cell-style|chart-value|simple-value|dataset-value)*>
        <!ATTLIST cell
                col CDATA #REQUIRED
                col-span CDATA #IMPLIED
                expand CDATA #REQUIRED
                link-target-window CDATA #IMPLIED
                name CDATA #REQUIRED
                row CDATA #REQUIRED>
        <!ELEMENT cell-style (left-border|right-border|top-border|bottom-border)*>
        <!ATTLIST cell-style
                align CDATA #REQUIRED
                bgcolor CDATA #IMPLIED
                bold CDATA #IMPLIED
                font-family CDATA #IMPLIED
                font-size CDATA #REQUIRED
                forecolor CDATA #IMPLIED
                valign CDATA #REQUIRED>
        <!ELEMENT left-border (#PCDATA)>
        <!ATTLIST left-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT right-border (#PCDATA)>
        <!ATTLIST right-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT top-border (#PCDATA)>
        <!ATTLIST top-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT bottom-border (#PCDATA)>
        <!ATTLIST bottom-border
                color CDATA #REQUIRED
                style CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT chart-value (dataset)*>
        <!ELEMENT dataset (sql|field)*>
        <!ATTLIST dataset
                category-property CDATA #IMPLIED
                collect-type CDATA #IMPLIED
                dataset-name CDATA #IMPLIED
                name CDATA #IMPLIED
                series-property CDATA #IMPLIED
                series-text CDATA #IMPLIED
                series-type CDATA #IMPLIED
                type CDATA #REQUIRED
                value-property CDATA #IMPLIED>
        <!ELEMENT simple-value (#PCDATA)>
        <!ELEMENT dataset-value (#PCDATA)>
        <!ATTLIST dataset-value
                aggregate CDATA #REQUIRED
                dataset-name CDATA #REQUIRED
                mapping-type CDATA #REQUIRED
                order CDATA #REQUIRED
                property CDATA #REQUIRED>
        <!ELEMENT row (#PCDATA)>
        <!ATTLIST row
                height CDATA #REQUIRED
                row-number CDATA #REQUIRED>
        <!ELEMENT column (#PCDATA)>
        <!ATTLIST column
                col-number CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT datasource (dataset)*>
        <!ATTLIST datasource
                name CDATA #REQUIRED
                type CDATA #REQUIRED
                username CDATA #REQUIRED
                password CDATA #REQUIRED
                url CDATA #REQUIRED
                driver CDATA #REQUIRED>
        <!ELEMENT sql (#PCDATA)>
        <!ELEMENT field (#PCDATA)>
        <!ATTLIST field
                name CDATA #REQUIRED>
        <!ELEMENT paper (#PCDATA)>
        <!ATTLIST paper
                type CDATA #REQUIRED
                left-margin CDATA #REQUIRED
                right-margin CDATA #REQUIRED
                top-margin CDATA #REQUIRED
                bottom-margin CDATA #REQUIRED
                paging-mode CDATA #REQUIRED
                fixrows CDATA #REQUIRED
                width CDATA #REQUIRED
                height CDATA #REQUIRED
                orientation CDATA #REQUIRED
                html-report-align CDATA #REQUIRED
                bg-image CDATA #REQUIRED
                html-interval-refresh-value CDATA #REQUIRED
                column-enabled CDATA #REQUIRED>
        ]>
<ureport><cell expand="None" name="A1" row="1" col="1" col-span="4" link-target-window="_parent"><cell-style font-size="10" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><chart-value><dataset dataset-name="test" type="pie" category-property="name" series-property="name" series-type="text" series-text="测试统计" value-property="position" collect-type="select"/></chart-value></cell><cell expand="None" name="E1" row="1" col="5" col-span="4"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><chart-value><dataset dataset-name="test" type="line" category-property="name" series-type="text" series-text="任务处理曲线图" value-property="position" collect-type="select"/></chart-value></cell><cell expand="None" name="A2" row="2" col="1" col-span="4"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><chart-value><dataset dataset-name="test" type="bar" category-property="name" series-type="text" series-text="对比数据" value-property="position" collect-type="select"/></chart-value></cell><cell expand="None" name="E2" row="2" col="5" col-span="4"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><chart-value><dataset dataset-name="test" type="radar" category-property="name" series-type="text" series-text="比较突出" value-property="position" collect-type="count"/></chart-value></cell><cell expand="None" name="A3" row="3" col="1" col-span="8"><cell-style font-size="19" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[任务统计]]></simple-value></cell><cell expand="None" name="A4" row="4" col="1"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[ID]]></simple-value></cell><cell expand="None" name="B4" row="4" col="2"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[name]]></simple-value></cell><cell expand="None" name="C4" row="4" col="3"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[description]]></simple-value></cell><cell expand="None" name="D4" row="4" col="4"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[is_in_chlog]]></simple-value></cell><cell expand="None" name="E4" row="4" col="5"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[position]]></simple-value></cell><cell expand="None" name="F4" row="4" col="6"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[is_in_roadmap]]></simple-value></cell><cell expand="None" name="G4" row="4" col="7"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[fields_bits]]></simple-value></cell><cell expand="None" name="H4" row="4" col="8"><cell-style font-size="9" forecolor="255,255,255" font-family="宋体" bgcolor="53,89,219" bold="true" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><simple-value><![CDATA[defaut_status_id]]></simple-value></cell><cell expand="Down" name="A5" row="5" col="1"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="id" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="B5" row="5" col="2"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="name" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="C5" row="5" col="3"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="description" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="D5" row="5" col="4"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="is_in_chlog" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="E5" row="5" col="5"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="position" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="F5" row="5" col="6"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="is_in_roadmap" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="G5" row="5" col="7"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="fields_bits" order="none" mapping-type="simple"></dataset-value></cell><cell expand="Down" name="H5" row="5" col="8"><cell-style font-size="9" forecolor="0,0,0" font-family="宋体" align="center" valign="middle"><left-border width="1" style="solid" color="0,0,0"/><right-border width="1" style="solid" color="0,0,0"/><top-border width="1" style="solid" color="0,0,0"/><bottom-border width="1" style="solid" color="0,0,0"/></cell-style><dataset-value dataset-name="test" aggregate="group" property="default_status_id" order="none" mapping-type="simple"></dataset-value></cell><row row-number="1" height="164"/><row row-number="2" height="151"/><row row-number="3" height="65"/><row row-number="4" height="19"/><row row-number="5" height="19"/><column col-number="1" width="137"/><column col-number="2" width="137"/><column col-number="3" width="137"/><column col-number="4" width="137"/><column col-number="5" width="137"/><column col-number="6" width="137"/><column col-number="7" width="137"/><column col-number="8" width="137"/><datasource name="grafana" type="jdbc" username="root" password="password" url="jdbc:mysql://mysql.eazybuilder-devops.cn:3306/grafana?useUnicode=true&amp;useSSL=false&amp;characterEncoding=utf-8" driver="com.mysql.cj.jdbc.Driver"><dataset name="test" type="sql"><sql><![CDATA[SELECT id, name, description, is_in_chlog, `position`, is_in_roadmap, fields_bits, default_status_id
FROM grafana.redmine_trackers]]></sql><field name="id"/><field name="name"/><field name="description"/><field name="is_in_chlog"/><field name="position"/><field name="is_in_roadmap"/><field name="fields_bits"/><field name="default_status_id"/></dataset></datasource><paper type="A4" left-margin="90" right-margin="90"
                                                                                                                                                                                                                                                                                 top-margin="72" bottom-margin="72" paging-mode="fitpage" fixrows="0"
                                                                                                                                                                                                                                                                                 width="595" height="842" orientation="portrait" html-report-align="left" bg-image="" html-interval-refresh-value="0" column-enabled="false"></paper></ureport>